server:
  port: 8084

spring:
  application:
    name: service-activation
  datasource:
    url: jdbc:postgresql://localhost:5435/servicedb
    username: postgres
    password: Yasuri@123
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092